name: Test

on:
    push:
      branches:
        - main
    workflow_dispatch:

jobs:
    Test:
        runs-on: ubuntu-22.04

        strategy:
            matrix:
              os: [fedora-39, fedora-40]
        steps:
            - name: Install requir packages
              run: |
                sudo dnf makecache
                sudo dnf -y install wget
                sudo dnf -y install tar
            - name: Test
              run: |
                bash ./install_fedora_auto.sh